language: python
python:
  - "3.4"
addons:
  apt:
    packages:
    - python3-dev
    - python-mysqldb
before_install:
  - mysql -e "create database IF NOT EXISTS jtx_test;" -uroot
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install mysqlclient"
script: "coverage run --source='.' --omit='jtx/wsgi.py,jtx/settings/*,*/migrations/*,*/__init__.py,manage.py' manage.py test --setings=jtx.settings.travis"
after_success: coveralls

notifications:
  irc:
    channels:
      - "irc.rezosup.org#jtx-dev"
    template:
      - "%{repository_name}/%{branch} %{commit} %{author}: %{message}"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
